namespace OVOCALIDAD.Shared.Constants;

public static class StoredProcedures
{
    public const string SP_OBTENER_VERSION_VIGENTE = "SP_OBTENER_VERSION_VIGENTE";
    public const string SP_OBTENER_SIGUIENTE_CORRELATIVO = "SP_OBTENER_SIGUIENTE_CORRELATIVO";
    public const string SP_GENERAR_LOTE = "SP_GENERAR_LOTE";
    public const string SP_LISTAR_LOTES = "SP_LISTAR_LOTES";
    public const string SP_OBTENER_CATALOGOS_LOTE = "SP_OBTENER_CATALOGOS_LOTE";
    public const string SP_OBTENER_DETALLE_LOTE = "SP_OBTENER_DETALLE_LOTE";

    public const string SP_CREAR_ESPECIFICACION_TECNICA = "SP_CREAR_ESPECIFICACION_TECNICA";
    public const string SP_OBTENER_CATALOGOS_ET = "SP_OBTENER_CATALOGOS_ET";
    public const string SP_OBTENER_SECCIONES_ET = "SP_OBTENER_SECCIONES_ET";
    public const string SP_CREAR_SECCION_ET = "SP_CREAR_SECCION_ET";
    public const string SP_AGREGAR_SECCION_VERSION_ET = "SP_AGREGAR_SECCION_VERSION_ET";
    public const string SP_QUITAR_SECCION_VERSION_ET = "SP_QUITAR_SECCION_VERSION_ET";
    public const string SP_REORDENAR_SECCIONES_VERSION_ET = "SP_REORDENAR_SECCIONES_VERSION_ET";
    public const string SP_GUARDAR_CONTENIDO_SECCION_ET = "SP_GUARDAR_CONTENIDO_SECCION_ET";
    public const string SP_OBTENER_CONTENIDO_SECCIONES_ET = "SP_OBTENER_CONTENIDO_SECCIONES_ET";
    public const string SP_LISTAR_ESPECIFICACIONES_TECNICAS = "SP_LISTAR_ESPECIFICACIONES_TECNICAS";
    public const string SP_OBTENER_ESPECIFICACION_TECNICA = "SP_OBTENER_ESPECIFICACION_TECNICA";
    public const string SP_GUARDAR_INFORMACION_GENERAL_ET = "SP_GUARDAR_INFORMACION_GENERAL_ET";
    public const string SP_GUARDAR_CARACTERISTICA_ET = "SP_GUARDAR_CARACTERISTICA_ET";
    public const string SP_ELIMINAR_CARACTERISTICA_ET = "SP_ELIMINAR_CARACTERISTICA_ET";
    public const string SP_CAMBIAR_ESTADO_VERSION_ET = "SP_CAMBIAR_ESTADO_VERSION_ET";

    public const string SP_CREAR_EVALUACION = "SP_CREAR_EVALUACION";
    public const string SP_INICIAR_EVALUACION = "SP_INICIAR_EVALUACION";
    public const string SP_OBTENER_PANEL_EVALUADOR = "SP_OBTENER_PANEL_EVALUADOR";
    public const string SP_OBTENER_EVALUACION = "SP_OBTENER_EVALUACION";
    public const string SP_GUARDAR_RESULTADO = "SP_GUARDAR_RESULTADO";
    public const string SP_CERRAR_EVALUACION = "SP_CERRAR_EVALUACION";
    public const string SP_TERMINAR_EVALUACION = "SP_TERMINAR_EVALUACION";
    public const string SP_SOLICITAR_REAPERTURA_EVALUACION = "SP_SOLICITAR_REAPERTURA_EVALUACION";
    public const string SP_RESOLVER_REAPERTURA_EVALUACION = "SP_RESOLVER_REAPERTURA_EVALUACION";

    public const string SP_OBTENER_ACCESOS_USUARIO = "SP_OBTENER_ACCESOS_USUARIO";
    public const string SP_OBTENER_NOTIFICACIONES_USUARIO = "SP_OBTENER_NOTIFICACIONES_USUARIO";
    public const string SP_MARCAR_NOTIFICACION_LEIDA = "SP_MARCAR_NOTIFICACION_LEIDA";
    public const string SP_MARCAR_NOTIFICACIONES_MODAL_MOSTRADAS = "SP_MARCAR_NOTIFICACIONES_MODAL_MOSTRADAS";
    public const string SP_GENERAR_NOTIFICACIONES_REVISION_ET = "SP_GENERAR_NOTIFICACIONES_REVISION_ET";

    public const string SP_OBTENER_USUARIO_AUTENTICACION = "SP_OBTENER_USUARIO_AUTENTICACION";
    public const string SP_ACTUALIZAR_ULTIMO_ACCESO = "SP_ACTUALIZAR_ULTIMO_ACCESO";
}
