namespace OVOCALIDAD.Shared.Constants;

public static class StoredProcedures
{
    public const string SP_OBTENER_VERSION_VIGENTE = "SP_OBTENER_VERSION_VIGENTE";
    public const string SP_OBTENER_SIGUIENTE_CORRELATIVO = "SP_OBTENER_SIGUIENTE_CORRELATIVO";
    public const string SP_GENERAR_LOTE = "SP_GENERAR_LOTE";
    public const string SP_LISTAR_LOTES = "SP_LISTAR_LOTES";
    public const string SP_OBTENER_CATALOGOS_LOTE = "SP_OBTENER_CATALOGOS_LOTE";
    public const string SP_OBTENER_DETALLE_LOTE = "SP_OBTENER_DETALLE_LOTE";

    public const string SP_CREAR_ESPECIFICACION_TECNICA = "SP_CREAR_ESPECIFICACION_TECNICA";
    public const string SP_OBTENER_CATALOGOS_ET = "SP_OBTENER_CATALOGOS_ET";
    public const string SP_LISTAR_ESPECIFICACIONES_TECNICAS = "SP_LISTAR_ESPECIFICACIONES_TECNICAS";
    public const string SP_OBTENER_ESPECIFICACION_TECNICA = "SP_OBTENER_ESPECIFICACION_TECNICA";
    public const string SP_GUARDAR_INFORMACION_GENERAL_ET = "SP_GUARDAR_INFORMACION_GENERAL_ET";
    public const string SP_GUARDAR_CARACTERISTICA_ET = "SP_GUARDAR_CARACTERISTICA_ET";
    public const string SP_ELIMINAR_CARACTERISTICA_ET = "SP_ELIMINAR_CARACTERISTICA_ET";

    public const string SP_CREAR_EVALUACION = "SP_CREAR_EVALUACION";
    public const string SP_INICIAR_EVALUACION = "SP_INICIAR_EVALUACION";
    public const string SP_OBTENER_EVALUACION = "SP_OBTENER_EVALUACION";
    public const string SP_GUARDAR_RESULTADO = "SP_GUARDAR_RESULTADO";
    public const string SP_CERRAR_EVALUACION = "SP_CERRAR_EVALUACION";
}
